Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
  # Customize your Aurora Serverless cluster by setting the default value of the following parameters.
  temporaldbclusterDBName:
    Type: String
    Description: The name of the initial database to be created in the DB cluster.
    Default: temporal
    # Cannot have special characters
    # Naming constraints: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  temporaldbclusterDBAutoPauseSeconds:
    Type: Number
    Description: The duration in seconds before the cluster pauses.
    Default: 1000
Mappings:
  temporaldbclusterEnvScalingConfigurationMap:
    develop:
      "DBMinCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBMaxCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]

    All:
      "DBMinCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBMaxCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]

Resources:
  temporaldbclusterDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: Group of Copilot private subnets for Aurora cluster.
      SubnetIds:
        !Split [",", { "Fn::ImportValue": !Sub "${App}-${Env}-PrivateSubnets" }]
  temporaldbclusterSecurityGroup:
    Metadata:
      "aws:copilot:description": "A security group for your workload to access the DB cluster temporaldbcluster"
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub "The Security Group for ${Name} to access DB cluster temporaldbcluster."
      VpcId:
        Fn::ImportValue: !Sub "${App}-${Env}-VpcId"
      Tags:
        - Key: Name
          Value: !Sub "copilot-${App}-${Env}-${Name}-Aurora"
  terSecurityGroup:
    Metadata:
      "aws:copilot:description": "A security group for your DB cluster temporaldbcluster"
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the database cluster.
      SecurityGroupIngress:
        - ToPort: 5432
          FromPort: 5432
          IpProtocol: tcp
          Description: !Sub "From the Aurora Security Group of the workload ${Name}."
          SourceSecurityGroupId: !Ref temporaldbclusterSecurityGroup
      VpcId:
        Fn::ImportValue: !Sub "${App}-${Env}-VpcId"
  temporaldbclusterAuroraSecret:
    Metadata:
      "aws:copilot:description": "A Secrets Manager secret to store your DB credentials"
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub Aurora main user secret for ${AWS::StackName}
      Name: !Sub "tprl/${Env}/dbsecret"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
  temporaldbclusterDBClusterParameterGroup:
    Metadata:
      "aws:copilot:description": "A DB parameter group for engine configuration values"
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: !Ref "AWS::StackName"
      Family: "aurora-postgresql10"
      Parameters:
        client_encoding: "UTF8"
  temporaldbclusterDBCluster:
    Metadata:
      "aws:copilot:description": "The temporaldbcluster Aurora Serverless database cluster"
    Type: "AWS::RDS::DBCluster"
    Properties:
      MasterUsername:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref temporaldbclusterAuroraSecret,
            ":SecretString:username}}",
          ],
        ]
      MasterUserPassword:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref temporaldbclusterAuroraSecret,
            ":SecretString:password}}",
          ],
        ]
      DatabaseName: !Ref temporaldbclusterDBName
      Engine: "aurora-postgresql"
      EngineVersion: "10.12"
      EngineMode: serverless
      DBClusterParameterGroupName: !Ref temporaldbclusterDBClusterParameterGroup
      DBSubnetGroupName: !Ref temporaldbclusterDBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref temporaldbclusterDBClusterSecurityGroup
      ScalingConfiguration:
        AutoPause: true
        # Replace "All" below with "!Ref Env" to set different autoscaling limits per environment.
        MinCapacity:
          !FindInMap [
            temporaldbclusterEnvScalingConfigurationMap,
            All,
            DBMinCapacity,
          ]
        MaxCapacity:
          !FindInMap [
            temporaldbclusterEnvScalingConfigurationMap,
            All,
            DBMaxCapacity,
          ]
        SecondsUntilAutoPause: !Ref temporaldbclusterDBAutoPauseSeconds
  temporaldbclusterSecretAuroraClusterAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref temporaldbclusterAuroraSecret
      TargetId: !Ref temporaldbclusterDBCluster
      TargetType: AWS::RDS::DBCluster
Outputs:
  temporaldbclusterSecret: # injected as TEMPORALDBCLUSTER_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref temporaldbclusterAuroraSecret
  temporaldbclusterSecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref temporaldbclusterSecurityGroup
